"use client";

import {
  DataVisualization,
  InteractiveSearch,
  PublicResources,
} from "@/components/sections/Experience";
import HeroSlideShow from "@/components/sections/HeroSlideShow";
import Intro from "@/components/sections/Intro";
import Overlay from "@/components/sections/Overlay";

const metadata = {
  title: "NHFR | Home",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div className=" flex flex-col gap-[5rem] md:gap-[5rem] ">
      <div>
        <HeroSlideShow />
      </div>
      <Overlay />
      <Intro />
      <InteractiveSearch />
      <DataVisualization />
      <PublicResources />
    </div>
  );
};
export default Home;
